name: "🔥 Cache Warming"

on:
  workflow_dispatch:
    inputs:
      variant:
        description: "Variant"
        type: choice
        default: "VANILLA"
        options:
          - "VANILLA"
      update_arsenal:
        description: "Refresh Arsenal"
        type: choice
        default: "no"
        options:
          - "yes"
          - "no"
      enable_lto:
        description: "⚠️ LTO"
        type: choice
        default: "THIN"
        options:
          - "NONE"
          - "THIN"

jobs:
  Luminaire:
    uses: ./.github/workflows/kernel-build.yml
    with:
      variant:        ${{ inputs.variant }}
      update_arsenal: ${{ inputs.update_arsenal }}
      enable_lto:     ${{ inputs.enable_lto }}
      warming_mode:   "true"
    secrets:
      PERSONAL_TOKEN:           ${{ secrets.PERSONAL_TOKEN }}
      TELEGRAM_BOT_TOKEN:       ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID:         ${{ secrets.TELEGRAM_CHAT_ID }}
      TELEGRAM_THREAD_ID_BUILD: ${{ secrets.TELEGRAM_THREAD_ID_BUILD }}
      TELEGRAM_THREAD_ID_LOG:   ${{ secrets.TELEGRAM_THREAD_ID_LOG }}
